# Site
name: "Humanities Data Inquiry"
title: "Home"
description: "Website of the Humanities Data Inquiry Project, hosted by the University of Lethbridge Humanities Innovation Lab."
logo: 'assets/images/156HDIFinch.png'
favicon: 'assets/images/HDIFinchSquare.ico'
baseurl: 
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dan:
    name: Daniel Paul O'Donnell
    display_name: Dan
    avatar: 'assets/images/standardHeadShot-small.png'
    gravatar: 
    email: daniel.odonnell@uleth.ca
    web: http://people.uleth.ca/~daniel.odonnell/
    twitter: https://twitter.com/danielpaulOD
    description: "Professor of English at the University of Lethbridge."
  khalid:
    name: Iftekhar Khalid
    display_name: Khalid 
    avatar: 'assets/images/avatar.png'
    gravatar: 
    email: 
    web: 
    twitter: 
    description: "."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
# this controls how many items appear in the blog section
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

#note the tabs are found in layouts.default.html
